// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcMclVGboq8dxlCseltaItn39gJ6cpF1U',
    appId: '1:705395804005:web:931b015da045026ee6438c',
    messagingSenderId: '705395804005',
    projectId: 'aquametric-ec4d5',
    authDomain: 'aquametric-ec4d5.firebaseapp.com',
    storageBucket: 'aquametric-ec4d5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6nMNdThhZpLAApewtf-qEiI3rbUXunSU',
    appId: '1:705395804005:android:4d916bc6cefb141be6438c',
    messagingSenderId: '705395804005',
    projectId: 'aquametric-ec4d5',
    storageBucket: 'aquametric-ec4d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW1YXUK1m4thJXQh-q3pFT1GmAzB-PRPg',
    appId: '1:705395804005:ios:83876aa925a362c1e6438c',
    messagingSenderId: '705395804005',
    projectId: 'aquametric-ec4d5',
    storageBucket: 'aquametric-ec4d5.firebasestorage.app',
    iosBundleId: 'com.example.aquametric',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW1YXUK1m4thJXQh-q3pFT1GmAzB-PRPg',
    appId: '1:705395804005:ios:83876aa925a362c1e6438c',
    messagingSenderId: '705395804005',
    projectId: 'aquametric-ec4d5',
    storageBucket: 'aquametric-ec4d5.firebasestorage.app',
    iosBundleId: 'com.example.aquametric',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcMclVGboq8dxlCseltaItn39gJ6cpF1U',
    appId: '1:705395804005:web:34d642b06b100362e6438c',
    messagingSenderId: '705395804005',
    projectId: 'aquametric-ec4d5',
    authDomain: 'aquametric-ec4d5.firebaseapp.com',
    storageBucket: 'aquametric-ec4d5.firebasestorage.app',
  );
}
